/* Copyright (C) 2023 Harry Clark */

/* SONIC THE HEDGEHOG (2006) Library */

/* THIS FILE PERTAINS TO THE MATHS UTILITY OF THE ENGINE DECOMP OF */
/* SONIC THE HEDGEHOG (2006) */

/* NESTED INCLUDES */

#include "geo.h"
#include "math_util.h"
#include "types.h"

/* SYSTEM INCLUDES */

#include <math.h>

/* ADDRESS THE VECTOR ADDRESS TO THE DESTINATION OF THE VECTOR */
/* AND IT'S ASSOCIATED ARRAY COMBINATION */

/* VECTORS ARE A COMBINATION OF VALUES RANGING FROM 0 TO 1 THAT */
/* HOUSE THE RELATIVE POSITION AND QUATERNION ROTATION OF AN OBJECT */

static inline void VECTOR_3_ADD(VEC_3 DESTINATION, VEC_3 ADDRESS)
{
    #ifdef VECTOR_ARRAYS

    DESTINATION[0] += ADDRESS[0];
    DESTINATION[1] += ADDRESS[1];
    DESTINATION[2] += ADDRESS[2];

    VECTOR_3_SET();

    #endif
}

/* FROM THE RELVANT FUNCTION CALL ABOVE, SET THE VECTOR POSITION AND ROTATION  */

static inline void VECTOR_3_SET(VEC_3 DESTINATION, VEC_3 X, VEC_3 Y, VEC_3 Z)
{
    #ifdef VECTOR_ARRAYS

    DESTINATION[0] += X[0];
    DESTINATION[1] += Y[1];
    DESTINATION[2] += Z[2];

    #endif
}
